version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: r:latest analysis/model.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        count_by_region: output/qfit_by_region.csv
        qfits_by_region: output/qfits_by_region.png
        fobts_by_region: output/fobts_by_region.png
        fobts_by_region_cat: output/fobts_by_region_cat.png
        fobts_by_region_cat_fit: output/fobts_by_region_cat_fit.png
        qfits_by_region_near_10: output/qfits_by_region_near_10.png
        qfit_months_by_region: output/qfit_months_by_region.png
  
  qfit_rmarkdown:
    run: r:latest -e 'rmarkdown::render("analysis/qfit_analysis.Rmd", output_dir = "output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        qfit_html: output/qfit_analysis.html
        
  qfit_region_rmarkdown:
    run: r:latest -e 'rmarkdown::render("analysis/qfit_analysis_region.Rmd", output_dir = "output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cum_prop_data: output/cum_prop_data.csv
        cum_prop_graph: output/cum_prop_graph.png
        cum_prop_data_all_ages: output/cum_prop_data_all_ages.csv
        cum_prop_graph_all_ages: output/cum_prop_graph_all_ages.png
        qfit_html: output/qfit_analysis_region.html
        n_by_region_period: output/n_by_region_period.csv
        n_by_region_month: output/n_by_region_month.csv

  qfit_region_rmarkdown_no_suppress:
    run: r:latest -e 'rmarkdown::render("analysis/qfit_analysis_region.Rmd", output_dir = "output", output_file = "qfit_analysis_region_no_suppress.html", params = list(suppress_if_le = FALSE))'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        qfit_html: output/qfit_analysis_region_no_suppress.html


  qfit_check_new_data:
    run: r:latest -e 'rmarkdown::render("analysis/check_new_fit_data.Rmd", output_dir = "output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        qfit_html: output/check_new_fit_data.html