version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: r:latest analysis/model.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        count_by_stp: output/qfit_by_stp.csv
        qfits_by_stp: output/qfits_by_stp.png
        fobts_by_stp: output/fobts_by_stp.png
        fobts_by_stp_cat: output/fobts_by_stp_cat.png
        fobts_by_stp_cat_fit: output/fobts_by_stp_cat_fit.png
        qfits_by_stp_near_10: output/qfits_by_stp_near_10.png
        qfit_months_by_stp: output/qfit_months_by_stp.png
  
  qfit_rmarkdown:
    run: r:latest -e 'rmarkdown::render("analysis/qfit_analysis.Rmd", output_dir = "output")'
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        qfit_html: output/qfit_analysis.html