version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: r:latest analysis/model.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        count_by_stp: output/qfit_by_stp.csv
        qfits_by_stp_log: output/qfits_by_stp_log_scale.png
        fobts_by_stp_log: output/fobts_by_stp_log_scale.png
        fobts_by_stp_cat: output/fobts_by_stp_cat.png
        qfits_by_stp_near_10: output/qfits_by_stp_near_10.png
        qfit_months_by_stp: output/qfit_months_by_stp.png