---
title: "Check out assumptions regarding FIT"
author: "Nick Kennedy"
date: "05/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(lubridate)
library(rlang)
source("sro_gastro_functions.R")
walk(list.files("firsttable/R", full.names = TRUE), source)
flip_first_table <- function(x) {
  x %>% as.data.frame() %>%
    select(-Level) %>%
    column_to_rownames("Variable") %>%
    t() %>%
    as.data.frame()
}
```

```{r load data}
input <- read_csv("../output/input.csv", col_types = cols(.default = col_character())) %>% 
  mutate(
    across(matches("^(qfit|ft.*|crc.*)_date$"), lubridate::ymd),
    across(c(ft_referral, ft_clinic, crc_diagnosis), ~as.logical(as.integer(.x))),
    across(c(qfit, age, fobt_num), as.numeric),
    qfit_num = if_else(is.na(qfit_date), NA_real_, qfit) +
      case_when(
        qfit_comp == "<" ~ -1,
        qfit_comp == ">" ~  1,
        TRUE             ~  0
      ),
    qfit_pos = qfit_num >= 10,
  )
```

```{r}
table(input$qfit_comp, input$region, useNA = "ifany")
table(input$qfit_ref_lower, input$region)
table(input$qfit_ref_lower, input$region)
input %>% filter(qfit_comp %in% c("<", ">")) %>% with(table(qfit, qfit_comp, region))
tapply(input$qfit_num, input$region, summary)
```