---
title: "qFIT OpenSafely analysis"
author: "Nick Kennedy"
date: "06/10/2021"
output:
  html_document:
      toc: true
      theme: cerulean
      df_print: kable
      dev: png
      fig_width: 12
      fig_height: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(lubridate)
library(rlang)
source("sro_gastro_functions.R")
walk(list.files("firsttable/R", full.names = TRUE), source)
flip_first_table <- function(x) {
  x %>% as.data.frame() %>%
    select(-Level) %>%
    column_to_rownames("Variable") %>%
    t() %>%
    as.data.frame()
}
```

```{r load data}
input <- read_csv("../output/input.csv", col_types = cols(.default = col_character())) %>% 
  mutate(
    across(matches("^(qfit|ft.*|crc.*)_date$"), lubridate::ymd),
    across(c(ft_referral, ft_clinic, crc_diagnosis), ~as.logical(as.integer(.x))),
    across(c(qfit, age, fobt_num), as.numeric),
    qfit_orig = if_else(is.na(qfit_date), NA_real_, qfit),
    qfit = qfit +
      case_when(
        qfit_comp == "<" ~ -1,
        qfit_comp == ">" ~  1,
        qfit_comp == "=" ~  0
      ),
    qfit_pos = qfit >= 10,
    qfit_pos_assume_zero_neg = case_when(
      !is.na(qfit) ~ qfit >= 10,
      qfit_orig == 0 ~ FALSE,
      TRUE ~ NA
    )
  )
cat("Data last updated at ", as.character(file.mtime("../output/input.csv")), "\n", sep = "")
cat("Analysis run at ", as.character(Sys.time()), "\n", sep = "")
```

# Top level summary by region

```{r}
ft_options <- first_table_options(include_denom = TRUE, percent_first = TRUE, include_p = FALSE, suppress_if_le = 5)
qfit_rows <- quos(
  "qFIT done and included here" = !is.na(qfit),
  "qFIT == 0 (including those with missing comparator)" = qfit_orig == 0,
  "qFIT == 0 (excluding those with missing comparator)" = first_table_row(qfit_orig == 0, data_filter = !is.na(qfit_comp)),
  "qFIT > 0" = qfit > 0,
  "qFIT >= 10" = qfit_pos,
  "Age" = age,
  "Age if qFIT done" = first_table_row(age, data_filter = !is.na(qfit)),
  "Age if qFIT neg" = first_table_row(age, data_filter = !qfit_pos),
  "Age if qFIT pos" = first_table_row(age, data_filter = qfit_pos),
  "Colorectal cancer" = crc_diagnosis,
  "Colorectal cancer if qFIT <= 10" = first_table_row(crc_diagnosis, data_filter = !qfit_pos),
  "Colorectal cancer if qFIT > 10" = first_table_row(crc_diagnosis, data_filter = qfit_pos),
  "FT referral" = ft_referral,
  "Colonoscopy" = !is.na(colonoscopy_sus),
  "Flexi sig" = !is.na(flexi_sig_sus),
  "Referral qFIT <= 10" = first_table_row(ft_referral, data_filter = !qfit_pos),
  "Referral qFIT > 10" = first_table_row(ft_referral, data_filter = qfit_pos),
  "Referral no qFIT" = first_table_row(ft_referral, data_filter = is.na(qfit_pos)),
  "qFIT refl timing" = first_table_row((qfit_date %--% ft_referral_date) / ddays(1), data_filter = !is.na(qfit)),
  "qFIT cscopy timing" = first_table_row((qfit_date %--% colonoscopy_sus) / ddays(1), data_filter = !is.na(qfit)),
  "qFIT flexi timing" = first_table_row((qfit_date %--% flexi_sig_sus) / ddays(1), data_filter = !is.na(qfit)),
  "qFIT diagnosis timing" = first_table_row((qfit_date %--% crc_diagnosis_date) / ddays(1), data_filter = !is.na(qfit))
)
first_table(
  input,
  .options = ft_options,
  .column_variable = region,
  !!!qfit_rows
)
```

## Restricted to <50 years old

```{r}
first_table(
  input %>% filter(age < 50),
  .options = ft_options,
  .column_variable = region,
  !!!qfit_rows
)
```

## Restricted to >=50 years old

```{r}
first_table(
  input %>% filter(age >= 50),
  .options = ft_options,
  .column_variable = region,
  !!!qfit_rows
)
```

## Top level summary by region (assuming zero is negative)

```{r}
first_table(
  input %>% mutate(qfit = qfit_pos_assume_zero_neg),
  .options = ft_options,
  .column_variable = region,
  !!!qfit_rows
)
```