---
title: "qFIT OpenSafely analysis"
author: "Nick Kennedy"
date: "12/07/2021"
output:
  html_document:
      toc: true
      theme: cerulean
      df_print: kable
      dev: png
      fig_width: 12
      fig_height: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(lubridate)
library(rlang)
source("sro_gastro_functions.R")
walk(list.files("firsttable/R", full.names = TRUE), source)
```

```{r load data}
input <- read_csv("../output/input.csv", col_types = cols(.default = col_character())) %>% 
  mutate(
    across(matches("^(qfit|ft.*|crc.*)_date$"), lubridate::ymd),
    across(c(ft_referral, ft_clinic, crc_diagnosis), ~as.logical(as.integer(.x))),
    across(c(qfit, age, fobt_num), as.numeric),
    qfit = if_else(is.na(qfit_date), NA_real_, qfit),
    qfit_pos = qfit > 10,
  )
```

# Top level summary by STP

```{r}
ft_options <- first_table_options(include_denom = TRUE, percent_first = TRUE, include_p = FALSE)
qfit_rows <- quos(
  "qFIT done" = !is.na(qfit_date),
  "qFIT > 0" = qfit > 0,
  "qFIT > 10" = qfit_pos,
  "Age" = age,
  "Age if qFIT done" = first_table_row(age, data_filter = !is.na(qfit_date)),
  "Age if qFIT neg" = first_table_row(age, data_filter = !qfit_pos),
  "Age if qFIT pos" = first_table_row(age, data_filter = qfit_pos),
  "Colorectal cancer" = crc_diagnosis,
  "Colorectal cancer if qFIT <= 10" = first_table_row(crc_diagnosis, data_filter = !qfit_pos),
  "Colorectal cancer if qFIT > 10" = first_table_row(crc_diagnosis, data_filter = qfit_pos)
)
first_table(
  input,
  .options = ft_options,
  .column_variable = stp,
  !!!qfit_rows
) %>% 
  as.data.frame()
```

## Restricted to <50 years old

```{r}
first_table(
  input %>% filter(age < 50),
  .options = ft_options,
  .column_variable = stp,
  !!!qfit_rows
) %>% 
  as.data.frame()
```

## Restricted to >=50 years old

```{r}
first_table(
  input %>% filter(age >= 50),
  .options = ft_options,
  .column_variable = stp,
  !!!qfit_rows
) %>% 
  as.data.frame()
```
